# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/Untitled/Cocos3/cocos-engine/native/external/sources/boost-source/container/CMakeLists.txt))

/Volumes/Untitled/Cocos3/cocos-engine/native/tools/simulator/build_full/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Volumes/Untitled/Cocos3/cocos-engine/native/tools/simulator/frameworks/runtime-src -B/Volumes/Untitled/Cocos3/cocos-engine/native/tools/simulator/build_full
